version: '3'

services:

  api:
    build: ./api
    ports:
      - 4001:4001
    environment:
      - GRAPHQL_LISTEN_PORT=4001
      - GRAPHQL_URI=http://api:4001/graphql
      - JWT_SECRET=abc
      - WEB_URI=http://localhost
    env_file:
      - ./api/.env
    volumes:
      - ./api:/app

  ui:
    build: ./ui-next
    volumes:
      - ./ui-next:/var/app
    ports:
      - '3000:3000'
    environment:
      - NEXT_TELEMETRY_DEBUG=1 # data will be printed but not sent to nextjs.org
      - WEB_URI=http://localhost
      - GRAPHQL_URI=http://api:4001/graphql
      - GRAPHQL_WEB_URI=http://localhost/graphql
    links:
      - api
    depends_on:
      - api

  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - ui
